// Fixed (non-computed) color keys for the Influence Analysis network graph
// and its Node/Edge Legend -- deliberately static rather than generated by
// makeCategoryColorScale() like the genre palettes elsewhere, because these
// two sets of categories (5 node types, 12 edge types) are small, fixed,
// and reused across every tab, so a hand-picked palette stays legible and
// consistent instead of being re-derived (and potentially reordered) per view.
export const NODE_COLORS = {
  Person: '#4a86e8',
  Song: '#f1c40f',
  Album: '#e74c3c',
  MusicalGroup: '#2ecc71',
  RecordLabel: '#c0392b',
}

export const EDGE_COLORS = {
  CoverOf: '#e67e22',
  ComposerOf: '#2980b9',
  DirectlySamples: '#16a085',
  InStyleOf: '#e67e22',
  InterpolatesFrom: '#8e44ad',
  LyricalReferenceTo: '#b7950b',
  LyricistOf: '#d4ac0d',
  MemberOf: '#2c3e50',
  PerformerOf: '#c0392b',
  ProducerOf: '#27ae60',
  RecordedBy: '#7f8c8d',
  DistributedBy: '#95a5a6',
}

export const ALL_NODE_TYPES = Object.keys(NODE_COLORS)
export const ALL_EDGE_TYPES = Object.keys(EDGE_COLORS)
